name: build

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          tags: |
            ghcr.io/chatbots-studio/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/chatbots-studio/${{ github.event.repository.name }}:latest
          cache-from: type=registry,ref=ghcr.io/chatbots-studio/${{ github.event.repository.name }}:latest
          cache-to: type=inline
